name: ligo
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alembic=1.13
  - annotated-types=0.7
  - anyio=4.4
  - argon2-cffi=23.1
  - argon2-cffi-bindings=21.2
  - arrow=1.3
  - asttokens=2.4
  - async-lru=2.0
  - async_generator=1.10
  - attrs=24.2
  - babel=2.14
  - beautifulsoup4=4.12
  - bleach=6.1
  - blinker=1.8
  - brotli-python=1.1
  - bzip2=1.0
  - ca-certificates=2024.7
  - cached-property=1.5
  - cached_property=1.5
  - certifi=2024.7
  - certipy=0.1
  - cffi=1.17
  - charset-normalizer=3.3
  - comm=0.2
  - cryptography=43.0
  - debugpy=1.8
  - decorator=5.1
  - defusedxml=0.7
  - entrypoints=0.4
  - exceptiongroup=1.2
  - executing=2.0
  - fqdn=1.5
  - greenlet=3.0
  - h11=0.14
  - h2=4.1
  - hpack=4.0
  - httpcore=1.0
  - httpx=0.27
  - hyperframe=6.0
  - icu=75.1
  - idna=3.8
  - importlib-metadata=8.4
  - importlib_metadata=8.4
  - importlib_resources=6.4
  - ipykernel=6.29
  - ipython=8.18
  - ipywidgets=8.1
  - isoduration=20.11
  - jedi=0.19
  - jinja2=3.1
  - json5=0.9
  - jsonpointer=3.0
  - jsonschema=4.23
  - jsonschema-specifications=2023.12
  - jsonschema-with-format-nongpl=4.23
  - jupyter-lsp=2.2
  - jupyter-offlinenotebook=0.3
  - jupyter-resource-usage=1.1
  - jupyter_client=8.6
  - jupyter_core=5.7
  - jupyter_events=0.10
  - jupyter_server=2.14
  - jupyter_server_terminals=0.5
  - jupyterhub-base=5.1
  - jupyterhub-singleuser=5.1
  - jupyterlab=4.2
  - jupyterlab_pygments=0.3
  - jupyterlab_server=2.27
  - jupyterlab_widgets=3.0
  - keyutils=1.6
  - krb5=1.21
  - ld_impl_linux-64=2.40
  - libedit=3.1
  - libffi=3.4
  - libgcc=14.1
  - libgcc-ng=14.1
  - libgomp=14.1
  - libnsl=2.0
  - libsodium=1.0
  - libsqlite=3.46
  - libstdcxx=14.1
  - libstdcxx-ng=14.1
  - libuuid=2.38
  - libuv=1.48
  - libxcrypt=4.4
  - libzlib=1.3
  - mako=1.3
  - markupsafe=2.1
  - matplotlib-inline=0.1
  - mistune=3.0
  - nbclient=0.10
  - nbconvert-core=7.16
  - nbformat=5.10
  - ncurses=6.5
  - nest-asyncio=1.6
  - nodejs=20.12
  - notebook=7.2
  - notebook-shim=0.2
  - oauthlib=3.2
  - openssl=3.3
  - overrides=7.7
  - packaging=24.1
  - pamela=1.2
  - pandocfilters=1.5
  - parso=0.8
  - pexpect=4.9
  - pickleshare=0.7
  - pip=24.2
  - pkgutil-resolve-name=1.3
  - platformdirs=4.2
  - prometheus_client=0.20
  - prompt-toolkit=3.0
  - psutil=5.9
  - ptyprocess=0.7
  - pure_eval=0.2
  - pycparser=2.22
  - pydantic=2.8
  - pydantic-core=2.20
  - pygments=2.18
  - pyjwt=2.9
  - pyopenssl=24.2
  - pysocks=1.7
  - python=3.9
  - python-dateutil=2.9
  - python-fastjsonschema=2.20
  - python-json-logger=2.0
  - python_abi=3.9
  - pytz=2024.1
  - pyyaml=6.0
  - pyzmq=26.2
  - readline=8.2
  - referencing=0.35
  - requests=2.32
  - rfc3339-validator=0.1
  - rfc3986-validator=0.1
  - rpds-py=0.20
  - send2trash=1.8
  - setuptools=72.2
  - six=1.16
  - sniffio=1.3
  - soupsieve=2.5
  - sqlalchemy=2.0
  - stack_data=0.6
  - terminado=0.18
  - tinycss2=1.3
  - tk=8.6
  - tomli=2.0
  - tornado=6.4
  - traitlets=5.14
  - types-python-dateutil=2.9
  - typing-extensions=4.12
  - typing_extensions=4.12
  - typing_utils=0.1
  - tzdata=2024a
  - uri-template=1.3
  - urllib3=2.2
  - wcwidth=0.2
  - webcolors=24.8
  - webencodings=0.5
  - websocket-client=1.8
  - wheel=0.44
  - widgetsnbextension=4.0
  - xz=5.2
  - yaml=0.2
  - zeromq=4.3
  - zipp=3.20
  - zlib=1.3
  - zstandard=0.23
  - zstd=1.5
  - pip:
      - contourpy==1.3
      - cycler==0.12
      - fonttools==4.55
      - h5py==3.12
      - kiwisolver==1.4
      - matplotlib==3.9
      - numpy==2.0
      - pillow==11.1
      - pyparsing==3.2
      - scipy==1.13